<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sudhersanansusa" failures="1" tests="6" name="Test" time="0.155" errors="0" timestamp="2022-04-24T13:23:13 IST">
  <testcase classname="com.Testng.Retry_concept" name="log_in" time="0.019">
    <skipped/>
  </testcase> <!-- log_in -->
  <testcase classname="com.Testng.Retry_concept" name="log_in" time="0.002">
    <skipped/>
  </testcase> <!-- log_in -->
  <testcase classname="com.Testng.Retry_concept" name="log_in" time="0.004">
    <skipped/>
  </testcase> <!-- log_in -->
  <testcase classname="com.Testng.Retry_concept" name="log_in" time="0.002">
    <skipped/>
  </testcase> <!-- log_in -->
  <testcase classname="com.Testng.Retry_concept" name="log_in" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [Susa6996] but found [susa6996]">
      <![CDATA[java.lang.AssertionError: expected [Susa6996] but found [susa6996]
at com.Testng.Retry_concept.log_in(Retry_concept.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- log_in -->
  <testcase classname="com.Testng.Retry_concept" name="password" time="0.005"/>
</testsuite> <!-- Test -->
